config/routes.rb
Rails.application.routes.draw do
  resources :videos
  get 'pages/contact'

  get 'pages/about'
	
	root 'videos#index'
	

end

app/models/video.rb
class Video < ActiveRecord::Base
	def next
		Video.where("id > ?", id).first
	end
	
	def prev
		Video.where("id < ?", id).last
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end

  def about
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json
  def index
    @videos = Video.all #get all video from Database @ video contains all videos from database
  end

  # GET /videos/1
  # GET /videos/1.json
  def show #renders the videos
		@videos = Video.all #REMEMBER THE ERROR!
		
		@next_video = @video.next
		@prev_video = @video.prev
  end

  # GET /videos/new
  def new
    @video = Video.new #action to create new video
  end

  # GET /videos/1/edit
  def edit
  end

  # POST /videos
  # POST /videos.json
  def create
    @video = Video.new(video_params)

    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:wistia, :description, :title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Codefornewbies</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>
  <nav>
    <div class="nav-wrapper">
			<%= link_to "CodeforNewbies", root_path, :class=>"brand-logo center " %>
         <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li>
        	<a href="<%= root_path %>"><i class="material-icons">view_list</i></a>
        	<a href="<%= pages_about_path %>"><i class="material-icons">perm_identity</i></a>
        	<a href="<%= pages_contact_path %>"><i class="material-icons">room</i></a>
        </li>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <a href="<%= root_path %>"><i class="material-icons">view_list</i></a>
        <a href="<%= pages_about_path %>"><i class="material-icons">perm_identity</i></a>
        <a href="<%= pages_contact_path %>"><i class="material-icons">room</i></a>
      </ul>
    </div>
  </nav>
  
<div class="row">
	<div class="col m10 offset-m1">
		<%= yield %>
	</div>
</div> 
	<script>$(".button-collapse").sideNav();</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">
	<h3>About me</h3>
	<div class="card z-depth-2">
		<div class="card-content white-text">
			<div class="row">
				<div class="col m6">
					<a class="twitter-timeline" data-height="500" data-theme="light" data-link-color="#E81C4F" href="https://twitter.com/Vooshi_">Tweets by Vooshi_</a> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
				</div>
				<div class="col m6">
					<div class="card-panel grey lighten-5 z-depth-1">
						<div class="row valign-wrapper">
							<div class="col m3">
								<%= image_tag "ME.jpg", class: "circle responsive-img" %>
							</div>
							<div class="col m9">
								<span class="black-text">
									Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, mollitia vitae atque. :) 
								</span>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<h3>Contact</h3>
	<div class="card z-depth-2">
		<div class="card-content">
			<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyC0IY0NH3EXwX-B_pNLBUnIVq6pA6ocDLo&callback=initMap"
							async defer></script>
			<script>
				var map;
				var myPos = {lat: 47.604061, lng: -122.3212237};
				function initMap() {
					map = new google.maps.Map(document.getElementById('map'), {
						center: myPos,
						zoom: 15,
					});
					var marker = new google.maps.Marker({
						position:myPos,
						title: "Home at last :)"
					});
					marker.setMap(map);
				}
			</script>
			<div id="map" style="height:500px; width:100%;"></div>

<!--			<iframe style="width:100%;" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/view?zoom=10&center=47.6062%2C-122.3321&key=AIzaSyC0IY0NH3EXwX-B_pNLBUnIVq6pA6ocDLo" allowfullscreen></iframe>-->
		</div>
	</div>
</div>

app/views/videos/_form.html.erb
<%= form_for(@video) do |f| %>
  <% if @video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@video.errors.count, "error") %> prohibited this video from being saved:</h2>

      <ul>
      <% @video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="input-field">
    <%= f.text_field :wistia, :placeholder => 'Link', :length => '10' %>
  </div>
   <div class="input-field">
    <%= f.text_field :title, :placeholder => 'Title', :length => '20' %>
  </div>
  <div class="input-field">
    <%= f.text_area :description, :placeholder => 'Description', :length => '800', :class => 'materialize-textarea' %>
  </div>
 	<button class="btn waves-effect waves-light" type="submit" name="action">Submit</button>
 	<a href="<%= videos_path %>" class="btn waves-effect waves-light" name="action">Back</a>
<% end %>

app/views/videos/edit.html.erb
<h1>Edit Video</h1>

<div class="container">
	<div class="card">
		<div class="card-content">
			<%= render 'form' %> 
		</div>
	</div>
</div>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Videos</h1>
<%= link_to new_video_path, :class => 'btn waves-effect waves-light' do %>
	<span>Add</span>
	<i class="material-icons left">open_in_new</i>
<% end %>
	<ul class="collapsible" data-collapsible="accordian">
		<% @videos.each do |video| %>
			<li class="">
				<div class="collapsible-header">
					<i class="material-icons">library_books</i>
					<%= link_to video.title, video %>
					<span class="right"><%= link_to edit_video_path(video) do %>
						<i class="material-icons">edit</i><% end %>
					<%= link_to video, method: :delete, data: { confirm: 'Are you sure you want to delete this video?' } do %>
						<i class="material-icons">cancel</i><% end %>
						</span>
			</div>
			<div class="collapsible-body"><p><%= video.description %></p></div>
			</li>
		<% end %>
	</ul>

app/views/videos/new.html.erb
<h1>New Video</h1>

<div class="container">
	<div class="card">
		<div class="card-content">
			<%= render 'form' %> 
		</div>
	</div>
</div>

app/views/videos/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">
	<div class="row">
		<div class="col m3">
			<div class="collection">
				<% @videos.each do |video| %>
				<%= link_to video.title, video, :class => 'collection-item' %>
				<% end %>
			</div>
		</div>
		<div class="col m9">
			<div class="card">
				<div class="card-content grey-text">
					<div class="card-image">
						<script src="//fast.wistia.com/assets/external/E-v1.js" async></script>
						<div class="wistia_embed wistia_async_<%= @video.wistia %>" style="height:500px; width:100%;
						"></div>
						<script>
							window._wq = window._wq || [];
							_wq.push({ "abc": function(video) {
								console.log("I got a handle to the video!", video);
									videoQuality: "hd-only",
									videoFoam: true
							}});
							function setPlaySpeed(r){
									video.playbackRate();
							}
						</script>
					</div>

					<span class="card-title"><%= @video.title %></span>
					<p><%= @video.description %></p>
					<button class="btn waves-effect waves-light btn-primary" onClick="setPlaySpeed(0.75);">0.75X</button>
					<button class="btn waves-effect waves-light btn-primary" onClick="setPlaySpeed(1);">1X</button>
					<button class="btn waves-effect waves-light btn-primary" onClick="setPlaySpeed(1.25);">1.25X</button>
					<button class="btn waves-effect waves-light btn-primary" onClick="setPlaySpeed(1.5);">1.5X</button>
					<button class="btn waves-effect waves-light btn-primary" onclick="setPlaySpeed(2)">2X</button>
				</div>
				<div class="card-action">
					<%= link_to "Previous", @prev_video if !@prev_video.nil? %>
					<span class="right"><%= link_to "Next", @next_video if !@next_video.nil? %></span>
				</div>
			</div>
		</div>
	</div>
</div>